### PR TITLE
Update DOHsinchu 201812 meetup

### PR DESCRIPTION
**Pull request by finch185277**
Add DOHsinchu 201812 meetup info

### CODE REVIEW

**Comment by kairen** [comment]
oh, I forgot my slide....

**Comment by kairen** [comment]
pls, add this https://speakerdeck.com/kairen/introduction-to-kubernetes-based-service-framework-and-project

**Comment by finch185277** [comment]
Already add slides URL.

**Comment by sufuf3** [comment]
Thank you

**Pull request merged**
